os: osx
osx_image: xcode9
language: objective-c

env:
  global:
    - PROJECT="UIDefaultFont.xcodeproj"
    matrix:
      - SCHEME="UIDefaultFont-iOS" DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.0" PLATFORM="iOS"
      - SCHEME="UIDefaultFont-iOS" DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=11.0" PLATFORM="iOS"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty

before_script:
  - open -b com.apple.iphonesimulator
  - carthage bootstrap --platform $PLATFORM

script:
  # Build Framework
  - set -o pipefail && xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty
  # Build Project with Package Managers
  - carthage build --platform $PLATFORM --no-skip-current
  - pod lib lint --swift-version=4.0
after_success:
  - bash <(curl -s https://codecov.io/bash)